### PR TITLE
Add ACE.

### PR DESCRIPTION
**Pull request by chriseth**
image

### CODE REVIEW

**Comment by chriseth** [comment]
Not sure if we should output the opcodes.

**Comment by chriseth** [comment]
Changed it to output assembly instead.

**Comment by franzihei** [comment]
Oh just realized you put the PR in the old repo, I moved the portal to its official home a few days ago! All new contributions have to go here: https://github.com/ethereum/solidity-portal

**Comment by franzihei** [comment]
Is there a way to copy PRs to other repos?

**Comment by chriseth** [comment]
Ah sorry, I did not realize that! Let me create a PR there.

**Pull request merged**
